// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGFPkblOwpDT4HERNS90Ofcfvum5jSxbg',
    appId: '1:1037719364189:web:d44af9e6c0f4c7475de3b4',
    messagingSenderId: '1037719364189',
    projectId: 'smart-plant-595ab',
    authDomain: 'smart-plant-595ab.firebaseapp.com',
    storageBucket: 'smart-plant-595ab.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGI6e1yHUtNwjbNUl80hHFTNR1Tr0ydIY',
    appId: '1:1037719364189:ios:05ca47bf6c5d4eb25de3b4',
    messagingSenderId: '1037719364189',
    projectId: 'smart-plant-595ab',
    storageBucket: 'smart-plant-595ab.firebasestorage.app',
    iosBundleId: 'com.example.smartPlanterApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGI6e1yHUtNwjbNUl80hHFTNR1Tr0ydIY',
    appId: '1:1037719364189:ios:05ca47bf6c5d4eb25de3b4',
    messagingSenderId: '1037719364189',
    projectId: 'smart-plant-595ab',
    storageBucket: 'smart-plant-595ab.firebasestorage.app',
    iosBundleId: 'com.example.smartPlanterApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCct5ax8gDhLF5Wrbl28dOWLiocxBVgC7E',
    appId: '1:1037719364189:android:da1cde5d194ff44f5de3b4',
    messagingSenderId: '1037719364189',
    projectId: 'smart-plant-595ab',
    storageBucket: 'smart-plant-595ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGFPkblOwpDT4HERNS90Ofcfvum5jSxbg',
    appId: '1:1037719364189:web:529c1617bec28ac95de3b4',
    messagingSenderId: '1037719364189',
    projectId: 'smart-plant-595ab',
    authDomain: 'smart-plant-595ab.firebaseapp.com',
    storageBucket: 'smart-plant-595ab.firebasestorage.app',
  );

}